import React from 'react';
import { motion } from 'framer-motion';
import { ShieldCheck, ShieldAlert, AlertTriangle, AlertOctagon, Info } from 'lucide-react';

const RISK_CONFIGS = {
  safe: {
    colorClass: 'bg-emerald-950/40 text-emerald-400 border-emerald-500/30',
    headerBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    icon: ShieldCheck,
    label: 'SAFE',
  },
  low_risk: {
    colorClass: 'bg-lime-950/40 text-lime-400 border-lime-500/30',
    headerBg: 'bg-lime-500/20 text-lime-300 border-lime-500/40',
    icon: Info,
    label: 'LOW RISK',
  },
  moderate_risk: {
    colorClass: 'bg-amber-950/40 text-amber-400 border-amber-500/30',
    headerBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    icon: AlertTriangle,
    label: 'MODERATE RISK',
  },
  high_risk: {
    colorClass: 'bg-orange-950/40 text-orange-400 border-orange-500/30',
    headerBg: 'bg-orange-500/20 text-orange-300 border-orange-500/40',
    icon: ShieldAlert,
    label: 'HIGH RISK',
  },
  critical: {
    colorClass: 'bg-red-950/40 text-red-400 border-red-500/30',
    headerBg: 'bg-red-500/20 text-red-300 border-red-500/40',
    icon: AlertOctagon,
    label: 'CRITICAL THREAT',
  },
};

export const VerdictCard = ({ verdict }) => {
  if (!verdict) return null;

  const riskKey = (verdict.risk_level || 'safe').toLowerCase();
  const config = RISK_CONFIGS[riskKey] || RISK_CONFIGS.safe;
  const IconComponent = config.icon;

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
      className={`rounded-2xl border ${config.colorClass} overflow-hidden shadow-xl`}
    >
      {/* Header bar */}
      <div className={`px-6 py-4 flex items-center justify-between border-b ${config.headerBg} font-display font-bold`}>
        <div className="flex items-center gap-3">
          <IconComponent className="w-6 h-6" />
          <span className="text-lg font-bold tracking-wide">{verdict.risk_label || config.label}</span>
        </div>
        {verdict.is_experimental && (
          <span className="px-2.5 py-0.5 text-xs font-bold uppercase rounded-full bg-purple-500/30 text-purple-200 border border-purple-400/40">
            Experimental
          </span>
        )}
      </div>

      {/* Body content */}
      <div className="p-6 space-y-4 bg-surface/50">
        <div>
          <h4 className="text-[10px] font-mono uppercase tracking-wider font-bold text-slate-400 mb-1">
            ANALYSIS SUMMARY
          </h4>
          <p className="text-slate-200 text-sm leading-relaxed">{verdict.explanation}</p>
        </div>

        {verdict.scam_category && (
          <div>
            <span className={`inline-block text-xs font-medium px-3 py-1 rounded-md border ${config.headerBg}`}>
              Scam Category: <strong className="text-white">{verdict.scam_category.replace(/_/g, ' ')}</strong>
            </span>
          </div>
        )}

        {/* Mandatory Disclaimer */}
        <div className="pt-3 border-t border-border/60">
          <p className="text-xs text-slate-400 italic leading-normal">
            {verdict.disclaimer || "This assessment is generated by an automated AI security model and may not detect all digital threats."}
          </p>
        </div>
      </div>
    </motion.div>
  );
};
