import React from 'react';
import { ShieldCheck, ShieldAlert, AlertTriangle, AlertOctagon, Info } from 'lucide-react';

const RISK_CONFIGS = {
  safe: {
    colorClass: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    headerBg: 'bg-emerald-500/20 text-emerald-300',
    icon: ShieldCheck,
    label: 'Safe',
  },
  low_risk: {
    colorClass: 'bg-lime-500/10 text-lime-400 border-lime-500/30',
    headerBg: 'bg-lime-500/20 text-lime-300',
    icon: Info,
    label: 'Low Risk',
  },
  moderate_risk: {
    colorClass: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
    headerBg: 'bg-amber-500/20 text-amber-300',
    icon: AlertTriangle,
    label: 'Moderate Risk',
  },
  high_risk: {
    colorClass: 'bg-orange-500/10 text-orange-400 border-orange-500/30',
    headerBg: 'bg-orange-500/20 text-orange-300',
    icon: ShieldAlert,
    label: 'High Risk',
  },
  critical: {
    colorClass: 'bg-red-500/10 text-red-400 border-red-500/30',
    headerBg: 'bg-red-500/20 text-red-300',
    icon: AlertOctagon,
    label: 'Critical Threat',
  },
};

export const VerdictCard = ({ verdict }) => {
  if (!verdict) return null;

  const riskKey = (verdict.risk_level || 'safe').toLowerCase();
  const config = RISK_CONFIGS[riskKey] || RISK_CONFIGS.safe;
  const IconComponent = config.icon;

  return (
    <div className={`rounded-xl border ${config.colorClass} overflow-hidden shadow-lg transition-all`}>
      {/* Header bar */}
      <div className={`px-5 py-3.5 flex items-center justify-between ${config.headerBg} font-semibold`}>
        <div className="flex items-center gap-2.5">
          <IconComponent className="w-6 h-6" />
          <span className="text-lg font-bold tracking-wide">{verdict.risk_label || config.label}</span>
        </div>
        {verdict.is_experimental && (
          <span className="px-2.5 py-0.5 text-xs font-bold uppercase rounded-full bg-purple-500/30 text-purple-200 border border-purple-400/40">
            Experimental
          </span>
        )}
      </div>

      {/* Body content */}
      <div className="p-5 space-y-4 bg-surface/50">
        <div>
          <h4 className="text-xs uppercase tracking-wider font-semibold text-slate-400 mb-1">Analysis Summary</h4>
          <p className="text-slate-200 text-sm leading-relaxed">{verdict.explanation}</p>
        </div>

        {verdict.scam_category && (
          <div>
            <span className="inline-block text-xs font-medium px-2.5 py-1 rounded-md bg-slate-700/80 text-slate-300 border border-slate-600">
              Scam Category: <strong className="text-slate-100">{verdict.scam_category.replace('_', ' ')}</strong>
            </span>
          </div>
        )}

        {/* Mandatory Disclaimer */}
        <div className="pt-3 border-t border-slate-700/60">
          <p className="text-xs text-slate-400 italic leading-normal">
            {verdict.disclaimer || "This assessment is generated by an automated system and may not detect all threats."}
          </p>
        </div>
      </div>
    </div>
  );
};
